#!/usr/bin/env bash
# Reads er-triage-phase-1/.env and generates mockups/env.local.js
# (gitignored) so the static HTML mockups can pick up real Supabase
# credentials without a build step. Re-run this after editing .env.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
OUT_FILE="mockups/env.local.js"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "No .env file found at er-triage-phase-1/.env" >&2
  exit 1
fi

get_var() {
  grep -E "^$1=" "$ENV_FILE" | head -n1 | cut -d'=' -f2-
}

SUPABASE_URL=$(get_var SUPABASE_URL)
SUPABASE_KEY=$(get_var SUPABASE_KEY)

cat > "$OUT_FILE" <<EOF
// AUTO-GENERATED by scripts/gen-env-local.sh from .env — do not edit by hand.
// Gitignored: never commit this file.
window.SUPABASE_URL = "${SUPABASE_URL}";
window.SUPABASE_KEY = "${SUPABASE_KEY}";
EOF

echo "Wrote $OUT_FILE"
