#!/usr/bin/env bash
# Cloudflare Pages build command. Reads SUPABASE_URL / SUPABASE_KEY from the
# Cloudflare Pages dashboard-configured environment variables (Settings >
# Variables and secrets) and generates mockups/env.local.js at deploy time,
# mirroring what scripts/gen-env-local.sh does from a local .env file.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT_FILE="mockups/env.local.js"

: "${SUPABASE_URL:?SUPABASE_URL not set — configure it in Cloudflare Pages > Settings > Variables and secrets}"
: "${SUPABASE_KEY:?SUPABASE_KEY not set — configure it in Cloudflare Pages > Settings > Variables and secrets}"

cat > "$OUT_FILE" <<EOF
// AUTO-GENERATED by scripts/gen-env-cloudflare.sh from Cloudflare Pages
// environment variables — do not edit by hand.
window.SUPABASE_URL = "${SUPABASE_URL}";
window.SUPABASE_KEY = "${SUPABASE_KEY}";
EOF

echo "Wrote $OUT_FILE"
