// Shared auth gate for every screen except login.html.
// Loaded after the supabase-js CDN script and env.local.js.
//
// Two ways in, no login form for the second one:
//   1. Admin — signed in via login.html with email+password.
//   2. Trial user (recruiter) — arrives via a magic link generated by
//      scripts/generate-magic-link.js. supabase-js's detectSessionInUrl
//      (on by default) consumes the token straight off this page's URL,
//      so getSession() below already returns their session — no form,
//      no extra click.
//
// This is a UX-level gate only: it hides the page and redirects if there's
// no session, but a determined caller can still hit the N8N webhooks
// directly. Real enforcement is the JWT-verification step planned for the
// webhooks (P7-B, not yet built) — don't treat this as the security boundary.

(function hideUntilChecked() {
  document.documentElement.style.visibility = "hidden";
})();

function reveal() {
  document.documentElement.style.visibility = "";
}

(async function authGuard() {
  try {
    const SUPABASE_URL = window.SUPABASE_URL || "https://lcaslbfjygzniosaobue.supabase.co";
    const SUPABASE_KEY = window.SUPABASE_KEY || "NOKEY";
    window.authDb = window.authDb || supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
    const db = window.authDb;

    const { data: { session } } = await db.auth.getSession();

    if (!session) {
      const here = location.pathname.split("/").pop() + location.search;
      location.replace(`login.html?next=${encodeURIComponent(here)}`);
      return;
    }

    // Magic-link tokens always land here (index.html) — Supabase's Admin API
    // drops any subpath from redirectTo and always resolves to the bare
    // Site URL, regardless of what generate-magic-link.js requests. Forward
    // straight to the dashboard instead of revealing this overview page,
    // preserving the hash so dashboard.html's own auth-guard run picks up
    // the session normally. Scoped to index.html only — this must never
    // fire on other pages (e.g. an admin's normal password-login landing
    // on intake-normal.html should never be redirected elsewhere).
    if (location.hash.includes("access_token")) {
      const onIndexPage = location.pathname === "/" || location.pathname.endsWith("/index.html");
      if (onIndexPage) {
        location.replace("dashboard.html" + location.hash);
        return;
      }
      // Drop the hash once consumed so it never sits in the address bar or
      // gets copy-pasted onward.
      history.replaceState(null, "", location.pathname + location.search);
    }

    window.currentUser = session.user;
    // Reveal first — the pill is cosmetic, the page itself must never stay
    // hidden because of it. This resolves fast (cached session, no network
    // round-trip), often before <body> exists yet since this script runs
    // in <head> — appendChild would throw on a null body if run inline.
    reveal();
    injectSessionPillWhenReady(session.user);

    db.auth.onAuthStateChange((event) => {
      if (event === "SIGNED_OUT") location.replace("login.html");
    });
  } catch (err) {
    // Fail open on display, not silent-forever-hidden — this is documented
    // as a UX-level gate only, not the real security boundary, so a stuck
    // blank page is a worse outcome than briefly showing content on an
    // unexpected error here.
    console.error("auth-guard error:", err);
    reveal();
  }
})();

function injectSessionPillWhenReady(user) {
  const inject = () => {
    try {
      const pill = document.createElement("div");
      pill.style.cssText = "position:fixed;top:10px;right:14px;z-index:9999;background:rgba(15,23,42,0.85);color:#e2e8f0;font-size:11px;font-weight:600;padding:5px 10px;border-radius:20px;display:flex;align-items:center;gap:8px;box-shadow:0 2px 8px rgba(0,0,0,0.2);";
      pill.innerHTML = `<span>${user.email || "Signed in"}</span><button style="background:rgba(255,255,255,0.15);border:none;color:#e2e8f0;font-size:10px;font-weight:700;padding:3px 8px;border-radius:12px;cursor:pointer;">Sign out</button>`;
      pill.querySelector("button").addEventListener("click", async () => {
        await window.authDb.auth.signOut();
      });
      document.body.appendChild(pill);
    } catch (err) {
      console.error("auth-guard: session pill injection failed:", err);
    }
  };
  if (document.body) inject();
  else document.addEventListener("DOMContentLoaded", inject);
}
